cache:
  yarn: true
  directories:
    - node_modules

deploy:
  api_key: "$NPM_AUTH_TOKEN"
  email: "charles.w.rudolph@gmail.com"
  on:
    node: '8'
    tags: true
  provider: npm
  skip_cleanup: true

language: node_js

node_js:
  - 8
  - 6
  - 4

notifications:
  email: false

script: yarn run test

sudo: false
