cache:
  yarn: true
  directories:
    - node_modules

deploy:
  api_key: "$NPM_AUTH_TOKEN"
  email: "charles.w.rudolph@gmail.com"
  on:
    node: '12'
    tags: true
  provider: npm
  skip_cleanup: true

language: node_js

node_js:
  - 8
  - 10
  - 12

notifications:
  email: false

sudo: false
